# Generated by Django 3.1.3 on 2023-07-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230712_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_id',
        ),
    ]
